name: Build

on:
  pull_request:
  push:
    branches:
    - master
    tags: '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
    - '.github/**'
    - '!.github/workflows/build.yml'

env:
  java: 1.8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '${{ env.java }}'
    - uses: actions/checkout@v2
    - name: Build
      run: mvn package -Dmaven.test.skip=true


